/*
 * Copyright (c) CISIAD, UNED, Spain,  2019. Licensed under the GPLv3 licence
 * Unless required by applicable law or agreed to in writing,
 * this code is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OF ANY KIND.
 */
/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/*
 * HillClimberOptionsGUI.java Created on 15-sep-2011, 19:37:32
 */

package org.openmarkov.learning.algorithm.pc.gui;

import org.openmarkov.core.exception.InvalidArgumentException;
import org.openmarkov.core.exception.UnrecoverableException;
import org.openmarkov.core.io.database.CaseDatabase;
import org.openmarkov.core.model.network.ProbNet;
import org.openmarkov.learning.algorithm.pc.PCAlgorithm;
import org.openmarkov.learning.algorithm.pc.independencetester.ANMCausalDirectionTester;
import org.openmarkov.learning.algorithm.pc.independencetester.AdaptativeTester;
import org.openmarkov.learning.algorithm.pc.independencetester.CausalDirectionTester;
import org.openmarkov.learning.algorithm.pc.independencetester.CrossEntropyIndependenceTester;
import org.openmarkov.learning.algorithm.pc.independencetester.G2IndependenceTester;
import org.openmarkov.learning.algorithm.pc.independencetester.IndependenceTester;
import org.openmarkov.learning.core.algorithm.LearningAlgorithm;
import org.openmarkov.learning.gui.AlgorithmConfiguration;
import org.openmarkov.learning.gui.AlgorithmParametersDialog;

import javax.swing.*;
import java.util.ArrayList;

/**
 * This abstract class represents the dialog that shows the user the options and
 * parameters of the PC algorithm.
 *
 * @author joliva
 */
@AlgorithmConfiguration(algorithm = PCAlgorithm.class) public class PCParametersDialog
        extends AlgorithmParametersDialog {

    /** Localization key suffixes for each tester, in display order (first = default). */
    public static final String[] independenceTesters = {"CrossEntropy", "G2", "Adaptive"};
    private String independenceTester = independenceTesters[0];
    private String significanceLevel = "0.05";
    private boolean useANM = true;
    private javax.swing.JTextField significanceLevelText;
    private javax.swing.JComboBox<String> independenceTesterComboBox;
    private javax.swing.JCheckBox useANMCheckBox;
    
    /**
     * Creates new form PCOptionsGUI
     */
    public PCParametersDialog(JFrame parent, boolean modal) {
        super(parent, modal);
        setLocationRelativeTo(null);
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        JPanel jPanel1 = new JPanel();
        JLabel testerLabel = new JLabel();
        independenceTesterComboBox = new javax.swing.JComboBox<>();
        alphaText = new javax.swing.JTextField();
        JLabel jLabel7 = new JLabel();
        // Variables declaration
        JButton acceptButton = new JButton();
        JLabel jLabel8 = new JLabel();
        significanceLevelText = new javax.swing.JTextField();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(stringDatabase.getString("Learning.PC.Title"));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(stringDatabase.getString("Learning.PC.Title")));
        testerLabel.setText(stringDatabase.getString("Learning.PC.IndependenceTest"));
        // independenceTesterComboBox.setModel(new
        // javax.swing.DefaultComboBoxModel(LearningManager.independenceTesters));
        for (String testerKey : independenceTesters) {
            independenceTesterComboBox.addItem(stringDatabase.getString("Learning.PC." + testerKey));
        }
        alphaText.setText("0.5");
        jLabel7.setText(stringDatabase.getString("Learning.Alpha") + ":");
        jLabel7.setToolTipText(stringDatabase.getString("Learning.Alpha.Tooltip"));
        acceptButton.setText(stringDatabase.getString("Learning.Ok"));
        acceptButton.addActionListener(evt -> {
            try {
                acceptButtonActionPerformed(evt);
            } catch (InvalidArgumentException e) {
                throw new UnrecoverableException(e);
            }
        });
        jLabel8.setText(stringDatabase.getString("Learning.PC.SignificanceLevel") + ":");
        jLabel8.setToolTipText(stringDatabase.getString("Learning.PC.SignificanceLevel.Tooltip"));
        significanceLevelText.setText(significanceLevel);
        useANMCheckBox = new javax.swing.JCheckBox("Use ANM causal direction test (phase 3)");
        useANMCheckBox.setSelected(true);
        useANMCheckBox.setToolTipText("Orient remaining undirected links using the Additive Noise Model instead of an arbitrary acyclic order");
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addGroup(jPanel1Layout.createSequentialGroup().addGroup(
                                                                                     jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                  .addGroup(
                                                                                                          jPanel1Layout.createSequentialGroup()
                                                                                                                       .addContainerGap()
                                                                                                                       .addComponent(testerLabel)
                                                                                                                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                       .addComponent(independenceTesterComboBox,
                                                                                                                                     javax.swing.GroupLayout.PREFERRED_SIZE, 236,
                                                                                                                                     javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                  .addGroup(
                                                                                                          jPanel1Layout.createSequentialGroup()
                                                                                                                       .addGap(102, 102, 102)
                                                                                                                       .addComponent(acceptButton))
                                                                                                  .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                         .addContainerGap()
                                                                                                                         .addGroup(
                                                                                                                                 jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                              .addComponent(jLabel8)
                                                                                                                                              .addComponent(jLabel7))
                                                                                                                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                         .addGroup(
                                                                                                                                 jPanel1Layout
                                                                                                                                         .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                         .addComponent(significanceLevelText,
                                                                                                                                                       javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                                                                                                                                       javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                         .addComponent(alphaText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                       60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                             .addContainerGap(12, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                           .addGap(18, 18, 18)
                                                                           .addGroup(
                                                                                   jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(independenceTesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(testerLabel))
                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                                                           .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                  .addComponent(jLabel8)
                                                                                                  .addComponent(significanceLevelText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                           .addGroup(
                                                                                   jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel7)
                                                                                                .addComponent(alphaText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                           .addGap(11, 11, 11)
                                                                           .addComponent(acceptButton)
                                                                           .addContainerGap()));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup().addContainerGap()
                        .addComponent(useANMCheckBox)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(useANMCheckBox)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void acceptButtonActionPerformed(
            java.awt.event.ActionEvent evt) {
        applyAlpha();
        Double degreeAcc;
        try {
            degreeAcc = Double.parseDouble(significanceLevelText.getText());
        } catch (NumberFormatException e) {
            degreeAcc = null;
        }
        if (degreeAcc == null || degreeAcc < 0 || degreeAcc > 1) {
            throw new InvalidArgumentException(degreeAcc, "degreeAcc", "must between 0 and 1");
        }
        independenceTester = independenceTesterComboBox.getSelectedItem().toString();
        significanceLevel = significanceLevelText.getText();
        useANM = useANMCheckBox.isSelected();
        this.setVisible(false);
    }
    
    @Override public String getDescription() {
        return stringDatabase.getString("Learning.PC.IndependenceTest.Short") + ": " + independenceTesterComboBox
                .getSelectedItem() + "\r\n" + stringDatabase.getString("Learning.PC.SignificanceLevel") + ": "
                + significanceLevel + "\r\n" + stringDatabase.getString("Learning.Alpha") + ": " + alphaParameter
                + "\r\nANM causal direction: " + useANM;
    }
    
    public String getIndependenceTester() {
        return independenceTester;
    }

    public String getDegreeOfAccuracy() {
        return significanceLevel;
    }

    // End of variables declaration//GEN-END:variables
    
    @Override public LearningAlgorithm getInstance(ProbNet probNet, CaseDatabase database) {
        CausalDirectionTester directionTester = useANM ? new ANMCausalDirectionTester() : null;
        return new PCAlgorithm(probNet, database, Double.parseDouble(alphaParameter),
                               buildSelectedTester(), Double.parseDouble(significanceLevel), directionTester);
    }

    @Override
    public ArrayList<Object> getOptions() {
        ArrayList<Object> options = new ArrayList<>();
        options.add(Double.parseDouble(alphaParameter));
        options.add(buildSelectedTester());
        options.add(Double.parseDouble(significanceLevel));
        options.add(useANM ? new ANMCausalDirectionTester() : null);
        return options;
    }

    private IndependenceTester buildSelectedTester() {
        return switch (independenceTesterComboBox.getSelectedIndex()) {
            case 1 -> new G2IndependenceTester();
            case 2 -> new AdaptativeTester();
            default -> new CrossEntropyIndependenceTester();
        };
    }
}
