/*
 * Copyright (c) CISIAD, UNED, Spain,  2019. Licensed under the GPLv3 licence
 * Unless required by applicable law or agreed to in writing,
 * this code is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OF ANY KIND.
 */

package org.openmarkov.learning.algorithm.hillclimbing.gui;

import org.openmarkov.core.exception.InvalidArgumentException;
import org.openmarkov.core.exception.UnreachableException;
import org.openmarkov.core.exception.UnrecoverableException;
import org.openmarkov.core.io.database.CaseDatabase;
import org.openmarkov.core.model.network.ProbNet;
import org.openmarkov.learning.algorithm.hillclimbing.HillClimbingAlgorithm;
import org.openmarkov.learning.metric.Metric;
import org.openmarkov.learning.metric.annotation.MetricManager;
import org.openmarkov.learning.core.algorithm.LearningAlgorithm;
import org.openmarkov.learning.gui.AlgorithmConfiguration;
import org.openmarkov.learning.gui.AlgorithmParametersDialog;

import javax.swing.*;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.Set;

/**
 * This abstract class represents the dialog that shows the user the options and
 * parameters of the hill climber algorithm.
 *
 * @author joliva
 * @author Manuel Arias
 */
@SuppressWarnings("serial") @AlgorithmConfiguration(algorithm = HillClimbingAlgorithm.class)
public class HillClimbingParametersDialog
        extends AlgorithmParametersDialog {
    private final MetricManager metricManager;
    private String metric = "";
    // Variables declaration
    private javax.swing.JButton AcceptButton;
    private javax.swing.JLabel MetricLabel;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> metricComboBox;
    
    /**
     * Creates new form HillClimberOptionsGUI
     */
    public HillClimbingParametersDialog(JFrame parent, boolean modal) {
        super(parent, modal);
        setLocationRelativeTo(parent);
        metricManager = new MetricManager();
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings({"rawtypes", "unchecked"}) private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        MetricLabel = new javax.swing.JLabel();
        metricComboBox = new javax.swing.JComboBox<>();
        alphaText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AcceptButton = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(stringDatabase.getString("Learning.HillClimbing.Title"));
        setResizable(false);
        jPanel1.setBorder(
                javax.swing.BorderFactory.createTitledBorder(stringDatabase.getString("Learning.HillClimbing.Title")));
        MetricLabel.setText(stringDatabase.getString("Learning.HillClimbing.Metric"));
        Set<String> metricNames = metricManager.getAllMetricNames();
        metricComboBox.setModel(new javax.swing.DefaultComboBoxModel(metricNames.toArray()));
        // Set the K2 metric as default
        if (metricNames.contains("K2"))
            metricComboBox.setSelectedItem("K2");
        metric = metricComboBox.getSelectedItem().toString();
        alphaText.setText(alphaParameter);
        jLabel7.setText(stringDatabase.getString("Learning.Alpha"));
        jLabel7.setToolTipText(stringDatabase.getString("Learning.Alpha.Tooltip"));
        AcceptButton.setText(stringDatabase.getString("Learning.Ok"));
        AcceptButton.addActionListener(evt -> {
            try {
                acceptButtonActionPerformed(evt);
            } catch (InvalidArgumentException e) {
                throw new UnrecoverableException(e);
            }
        });
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addGroup(jPanel1Layout.createSequentialGroup().addGroup(
                                                                                     jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                  .addGroup(
                                                                                                          jPanel1Layout.createSequentialGroup()
                                                                                                                       .addContainerGap()
                                                                                                                       .addComponent(jLabel7)
                                                                                                                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                       .addComponent(alphaText, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                                                                                                     javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                  .addGroup(
                                                                                                          jPanel1Layout.createSequentialGroup()
                                                                                                                       .addGap(102, 102, 102)
                                                                                                                       .addComponent(AcceptButton))
                                                                                                  .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                                         .addContainerGap()
                                                                                                                         .addComponent(MetricLabel)
                                                                                                                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                         .addComponent(metricComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 193,
                                                                                                                                       javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                             .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                           .addGap(18, 18, 18)
                                                                           .addGroup(
                                                                                   jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(metricComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(MetricLabel))
                                                                           .addGap(18, 18, 18)
                                                                           .addGroup(
                                                                                   jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(alphaText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel7))
                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                                                           .addComponent(AcceptButton)
                                                                           .addContainerGap()));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addContainerGap()
                      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addContainerGap()
                      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void acceptButtonActionPerformed(
            java.awt.event.ActionEvent evt) {
        applyAlpha();
        metric = (String) metricComboBox.getSelectedItem();
        this.setVisible(false);
    }
    
    @Override public String getDescription() {
        return stringDatabase.getString("Learning.HillClimbing.Metric") + ": " + metric + "\r\n" + stringDatabase
                .getString("Learning.Alpha") + ": " + alphaParameter;
    }
    
    public String getMetric() {
        return metric;
    }
    
    @Override public LearningAlgorithm getInstance(ProbNet probNet, CaseDatabase database) {
        try {
            Metric metricInstance = null;
            Constructor<?>[] constructors = metricManager.getMetricByName(metric).getConstructors();
            for (Constructor<?> constructor : constructors) {
                Class<?>[] parameterTypes = constructor.getParameterTypes();
                if (parameterTypes.length == 1 && parameterTypes[0] == double.class)
                    metricInstance = (Metric) constructor.newInstance(Double.parseDouble(alphaParameter));
                else if (parameterTypes.length == 0)
                    metricInstance = (Metric) constructor.newInstance();
            }
            return new HillClimbingAlgorithm(probNet, database, Double.parseDouble(alphaParameter), metricInstance);
        } catch (InstantiationException | IllegalAccessException | InvocationTargetException e) {
            throw new UnreachableException(e);
        }
    }
    
    @Override public ArrayList<Object> getOptions() {
        ArrayList<Object> options = new ArrayList<>();
        options.add(Double.parseDouble(alphaParameter));
        try {
            Metric metricInstance = null;
            Constructor<?>[] constructors = metricManager.getMetricByName(metric).getConstructors();
            for (Constructor<?> constructor : constructors) {
                Class<?>[] parameterTypes = constructor.getParameterTypes();
                if (parameterTypes.length == 1 && parameterTypes[0] == double.class)
                    metricInstance = (Metric) constructor.newInstance(Double.parseDouble(alphaParameter));
                else if (parameterTypes.length == 0)
                    metricInstance = (Metric) constructor.newInstance();
            }
            options.add(metricInstance);
            return options;
        } catch (InstantiationException | IllegalAccessException | InvocationTargetException e) {
            throw new UnreachableException(e);
        }
    }
}
