/*
 * Copyright (c) CISIAD, UNED, Spain,  2019. Licensed under the GPLv3 licence
 * Unless required by applicable law or agreed to in writing,
 * this code is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OF ANY KIND.
 */

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InteractiveLearningGUI.java
 *
 * Created on 08-may-2011, 12:30:57
 */

package org.openmarkov.learning.gui.interactive;

import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.UnknownNullability;
import org.openmarkov.core.action.base.PNEdit;
import org.openmarkov.core.action.base.PNEditListener;
import org.openmarkov.core.exception.*;
import org.openmarkov.core.localize.StringDatabase;
import org.openmarkov.core.model.network.type.BayesianNetworkType;
import org.openmarkov.learning.core.LearningManager;
import org.openmarkov.learning.core.util.LearningEditProposal;
import org.openmarkov.learning.gui.interactive.EditProposalTable.EditSelectionListener;
import org.openmarkov.learning.gui.interactive.EditProposalTable.EditionEvent;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Inigo
 */
@SuppressWarnings("serial") public class InteractiveLearningDialog extends JDialog
        implements EditSelectionListener, PNEditListener {
    
    public static final int SHOWING_EDIT_NUM = 50;
    /**
     * String database
     */
    protected final StringDatabase stringDatabase = StringDatabase.getUniqueInstance();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnBlockEdit;
    private JButton btnEdit;
    private JButton btnNextPhase;
    private JButton btnRedo;
    private JButton btnRun;
    private JButton btnShowBlocked;
    private JButton btnUndo;
    private JCheckBox chkOnlyAllowedEdits;
    private JCheckBox chkOnlyPositiveEdits;
    private JScrollPane jScrollPane1;
    private JTable jTable1;
    private JLabel lblScore;
    private final EditProposalTable editionsTable;
    private final LearningManager learningManager;
    private boolean onlyAllowed = true, onlyPositive = true;
    private final BlockedEditDialog blockedEditDialog;
    private boolean learningFinished = false;
    
    /**
     * Creates new form InteractiveLearningGUI
     */
    public InteractiveLearningDialog(JFrame parent, boolean modal, LearningManager learningManager) {
        super(parent, modal);
        this.learningManager = learningManager;
        this.learningManager.getLearnedNet().getPNESupport().setWithUndo(true);
        this.learningManager.getLearnedNet().getPNESupport().addListener(this);
        editionsTable = new EditProposalTable();
        editionsTable.addEditSelectionListener(this);
        initComponents();
        jScrollPane1.setViewportView(editionsTable);
        updateEditionsTable(onlyAllowed, onlyPositive, learningManager.getBlockedEdits());
        if (parent != null) {
            this.setLocation(parent.getLocationOnScreen().x + parent.getSize().width - this.getSize().width,
                             140 + parent.getLocationOnScreen().y);
        }
        this.blockedEditDialog = new BlockedEditDialog(this, false);
    }
    
    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        btnEdit = new JButton();
        btnUndo = new JButton();
        chkOnlyAllowedEdits = new JCheckBox();
        chkOnlyPositiveEdits = new JCheckBox();
        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();
        btnRedo = new JButton();
        btnBlockEdit = new JButton();
        btnShowBlocked = new JButton();
        lblScore = new JLabel();
        btnRun = new JButton();
        btnNextPhase = new JButton();
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(stringDatabase.getString("Learning.Interactive.Title"));
        setResizable(true);
        setMinimumSize(new Dimension(650, 200));
        addWindowListener(new WindowAdapter() {
            @Override public void windowClosing(WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        
        btnEdit.setText(stringDatabase.getString("Learning.Interactive.ApplyEdit"));
        btnEdit.addActionListener(evt -> {
            try {
                btnEditActionPerformed(evt);
            } catch (DoEditException | CannotNormalizePotentialException |
                     IncompatibleEvidenceException.EvidenceIsIncompatibleWithOther | NonProjectablePotentialException |
                     NotEvaluableNetworkException.NotApplicableNetwork |
                     NotEvaluableNetworkException.UnsatisfiedConstraints e) {
                throw new UnrecoverableException(e);
            }
        });
        
        btnUndo.setText(stringDatabase.getString("Learning.Interactive.Undo"));
        btnUndo.setEnabled(false);
        btnUndo.addActionListener(new ActionListener() {
            @Override public void actionPerformed(ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });
        
        chkOnlyAllowedEdits.setSelected(true);
        chkOnlyAllowedEdits.setText(stringDatabase.getString("Learning.Interactive.OnlyAllowedEdits"));
        chkOnlyAllowedEdits.addChangeListener(new ChangeListener() {
            @Override public void stateChanged(ChangeEvent evt) {
                chkOnlyAllowedEditsStateChanged(evt);
            }
        });
        
        chkOnlyPositiveEdits.setSelected(true);
        chkOnlyPositiveEdits.setText(stringDatabase.getString("Learning.Interactive.OnlyPositiveEdits"));
        chkOnlyPositiveEdits.addChangeListener(new ChangeListener() {
            @Override public void stateChanged(ChangeEvent evt) {
                chkOnlyPositiveEditsStateChanged(evt);
            }
        });
        
        jTable1.setModel(new DefaultTableModel(
                new Object[][]{{null, null, null, null}, {null, null, null, null}, {null, null, null, null},
                        {null, null, null, null}}, new String[]{"Title 1", "Title 2", "Title 3", "Title 4"}));
        jScrollPane1.setViewportView(jTable1);
        
        btnRedo.setText(stringDatabase.getString("Learning.Interactive.Redo"));
        btnRedo.setEnabled(false);
        btnRedo.addActionListener(new ActionListener() {
            @Override public void actionPerformed(ActionEvent evt) {
                btnRedoActionPerformed(evt);
            }
        });
        
        btnBlockEdit.setText(stringDatabase.getString("Learning.Interactive.BlockEdit"));
        btnBlockEdit.addActionListener(new ActionListener() {
            @Override public void actionPerformed(ActionEvent evt) {
                btnBlockEditActionPerformed(evt);
            }
        });
        
        btnShowBlocked.setText(stringDatabase.getString("Learning.Interactive.ShowBlocked"));
        btnShowBlocked.addActionListener(new ActionListener() {
            @Override public void actionPerformed(ActionEvent evt) {
                btnShowBlockedActionPerformed(evt);
            }
        });
        
        lblScore.setText(stringDatabase.getString("Learning.Interactive.Score") + ": ");
        lblScore.setVisible(false);
        
        btnRun.setText(stringDatabase.getString("Learning.Interactive.Run"));
        btnRun.addActionListener(evt -> {
            try {
                btnRunActionPerformed(evt);
            } catch (RuntimeException e) {
                throw new UnrecoverableException(e);
            }
        });
        btnRun.setToolTipText(stringDatabase.getString("Learning.Interactive.Run.ToolTip"));
        
        btnNextPhase.setText(stringDatabase.getString("Learning.Interactive.NextPhase"));
        btnNextPhase.setToolTipText("");
        btnNextPhase.addActionListener(new ActionListener() {
            @Override public void actionPerformed(ActionEvent evt) {
                btnNextPhaseActionPerformed(evt);
            }
        });
        
        btnNextPhase.setToolTipText(stringDatabase.getString("Learning.Interactive.NextPhase.ToolTip"));
        
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addContainerGap().addGroup(
                              layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, 300, 500, Short.MAX_VALUE).addGroup(
                                            layout.createSequentialGroup()
                                                  .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
                                                                   GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                  .addComponent(btnEdit)
                                                  .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
                                                                   GroupLayout.DEFAULT_SIZE,
                                                                   GroupLayout.DEFAULT_SIZE).addComponent(btnUndo)
                                                  .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
                                                                   GroupLayout.DEFAULT_SIZE,
                                                                   GroupLayout.DEFAULT_SIZE).addComponent(btnRedo)
                                                  .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
                                                                   GroupLayout.DEFAULT_SIZE,
                                                                   GroupLayout.DEFAULT_SIZE).addComponent(btnNextPhase)
                                                  .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
                                                                   GroupLayout.DEFAULT_SIZE,
                                                                   GroupLayout.DEFAULT_SIZE).addComponent(btnRun)
                                                  .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
                                                                   GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                      .addGap(18, 18, 18).addGroup(
                              layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblScore).addGroup(
                                            layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                  .addComponent(btnBlockEdit, GroupLayout.Alignment.TRAILING,
                                                                GroupLayout.DEFAULT_SIZE,
                                                                GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                  .addComponent(btnShowBlocked, GroupLayout.Alignment.TRAILING))
                                    .addComponent(chkOnlyPositiveEdits).addComponent(chkOnlyAllowedEdits))
                      .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addContainerGap().addGroup(
                              layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(
                                            layout.createSequentialGroup().addComponent(chkOnlyAllowedEdits)
                                                  .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                  .addComponent(chkOnlyPositiveEdits)
                                                  .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                  .addComponent(btnBlockEdit).addGap(8, 8, 8).addComponent(btnShowBlocked))
                                    .addComponent(jScrollPane1, 50, 155, Short.MAX_VALUE))
                      .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addGroup(
                              layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(lblScore)
                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                    .addComponent(btnEdit).addComponent(btnUndo).addComponent(btnRedo)
                                                    .addComponent(btnRun).addComponent(btnNextPhase))).addContainerGap()));
        
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnEditActionPerformed(ActionEvent evt) throws DoEditException, IncompatibleEvidenceException.EvidenceIsIncompatibleWithOther, NonProjectablePotentialException, NotEvaluableNetworkException.NotApplicableNetwork, NotEvaluableNetworkException.UnsatisfiedConstraints {
        applySelected(); // applySelected() already calls updateUI() internally
    }
    
    private void btnUndoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        this.dontUpdateUIOnThisEdit = learningManager.getLearnedNet()
                                                     .getPNESupport()
                                                     .getCurrentEditHistory()
                                                     .nextEditToUndo();
        learningManager.getLearnedNet().getPNESupport().undo();
        this.dontUpdateUIOnThisEdit = null;
        updateUI();
    }//GEN-LAST:event_btnEditActionPerformed
    
    private void chkOnlyAllowedEditsStateChanged(
            ChangeEvent evt) {//GEN-FIRST:event_chkOnlyAllowedEditsStateChanged
        if (onlyAllowed != chkOnlyAllowedEdits.isSelected()) {
            onlyAllowed = chkOnlyAllowedEdits.isSelected();
            updateUI();
        }
    }//GEN-LAST:event_chkOnlyAllowedEditsStateChanged
    
    private void chkOnlyPositiveEditsStateChanged(
            ChangeEvent evt) {//GEN-FIRST:event_chkOnlyPositiveEditsStateChanged
        if (onlyPositive != chkOnlyPositiveEdits.isSelected()) {
            onlyPositive = chkOnlyPositiveEdits.isSelected();
            updateUI();
        }
    }//GEN-LAST:event_chkOnlyPositiveEditsStateChanged
    
    private void formWindowClosing(WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    }//GEN-LAST:event_formWindowClosing
    
    private void btnRedoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnRedoActionPerformed
        this.dontUpdateUIOnThisEdit = learningManager.getLearnedNet()
                                                     .getPNESupport()
                                                     .getCurrentEditHistory()
                                                     .nextEditToRedo();
        learningManager.getLearnedNet().getPNESupport().redo();
        this.dontUpdateUIOnThisEdit = null;
        updateUI();
    }//GEN-LAST:event_btnRedoActionPerformed
    
    private void btnBlockEditActionPerformed(
            ActionEvent evt) {//GEN-FIRST:event_btnBlockEditActionPerformed
        if (editionsTable.getSelectedEdit() != null) {
            learningManager.blockEdit(editionsTable.getSelectedEditProposal());
            updateUI();
        }
    }//GEN-LAST:event_btnBlockEditActionPerformed
    
    private void btnShowBlockedActionPerformed(
            ActionEvent evt) {//GEN-FIRST:event_btnShowBlockedActionPerformed
        blockedEditDialog.setLocation(this.getX() + this.getWidth() - blockedEditDialog.getWidth(),
                                      this.getY() + this.getHeight());
        blockedEditDialog.setVisible(true);
        updateUI();
    }//GEN-LAST:event_btnShowBlockedActionPerformed
    
    private void btnRunActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        if (!learningFinished) {
            learningManager.learn();
            this.setVisible(false);
        }
        this.setVisible(false);
    }//GEN-LAST:event_btnRunActionPerformed
    
    private void btnNextPhaseActionPerformed(
            ActionEvent evt) {//GEN-FIRST:event_btnNextPhaseActionPerformed
        learningManager.getLearnedNet().getPNESupport().removeListener(this);
        learningManager.goToNextPhase();
        updateEditionsTable(onlyAllowed, onlyPositive, learningManager.getBlockedEdits());
        learningManager.getLearnedNet().getPNESupport().addListener(this);
        updateUI();
    }//GEN-LAST:event_btnNextPhaseActionPerformed
    
    @Override
    public void editionPerformed(EditionEvent editionEvent) throws DoEditException, IncompatibleEvidenceException.EvidenceIsIncompatibleWithOther, NonProjectablePotentialException, NotEvaluableNetworkException.NotApplicableNetwork, NotEvaluableNetworkException.UnsatisfiedConstraints {
        applySelected();
    }
    // End of variables declaration//GEN-END:variables
    
    public void editionUnblocked(LearningEditProposal edit) {
        learningManager.unblockEdit(edit);
        updateUI();
    }
    
    private void applySelected() throws DoEditException, IncompatibleEvidenceException.EvidenceIsIncompatibleWithOther, NonProjectablePotentialException, NotEvaluableNetworkException.NotApplicableNetwork, NotEvaluableNetworkException.UnsatisfiedConstraints {
        if (editionsTable.getSelectedEdit() != null) {
            dontUpdateUIOnThisEdit = editionsTable.getSelectedEdit();
            learningManager.applyEdit(editionsTable.getSelectedEdit());
            dontUpdateUIOnThisEdit = null;
            updateUI();
        }
    }
    
    private @Nullable PNEdit dontUpdateUIOnThisEdit = null;
    
    public void updateUI() {
        updateEditionsTable(onlyAllowed, onlyPositive, learningManager.getBlockedEdits());
        btnRedo.setEnabled(learningManager.getLearnedNet().getPNESupport().getCurrentEditHistory().canRedo());
        btnUndo.setEnabled(learningManager.getLearnedNet().getPNESupport().getCurrentEditHistory().canUndo());
    }
    
    @Override public void afterEditExecutes(@UnknownNullability PNEdit edit) {
        if (dontUpdateUIOnThisEdit != edit) {
            updateUI();
        }
    }
    
    @Override public void afterUndoingEdit(PNEdit edit) {
        if (dontUpdateUIOnThisEdit != edit) {
            updateUI();
        }
    }
    
    private void updateEditionsTable(boolean onlyAllowed, boolean onlyPositive,
                                     List<LearningEditProposal> blockedEdits) {
        ArrayList<LearningEditProposal> showableEditProposals = new ArrayList<>();
        LearningEditProposal bestEdition = learningManager.getBestEdit(onlyAllowed, onlyPositive);
        while (showableEditProposals.size() < SHOWING_EDIT_NUM && bestEdition != null) {
            showableEditProposals.add(bestEdition);
            bestEdition = learningManager.getNextEdit(onlyAllowed, onlyPositive);
        }
        editionsTable.fill(showableEditProposals);
        if (showableEditProposals.isEmpty()) {
            try {
                learningManager.getLearnedNet().setNetworkType(BayesianNetworkType.getUniqueInstance());
            } catch (ConstraintViolatedException e) {
                throw new UnreachableException(e);
            }
            learningFinished = true;
        }
        if (blockedEditDialog != null) {
            List<LearningEditProposal> blockedEditProposals = new ArrayList<LearningEditProposal>(blockedEdits);
            blockedEditDialog.fill(blockedEditProposals);
        }
        var isFinished = learningFinished && showableEditProposals.isEmpty();
        btnNextPhase.setEnabled(!isFinished);
        btnEdit.setEnabled(!isFinished);
    }
}
