/*
 * Copyright (c) CISIAD, UNED, Spain,  2019. Licensed under the GPLv3 licence
 * Unless required by applicable law or agreed to in writing,
 * this code is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OF ANY KIND.
 */

package org.openmarkov.dbgenerator.gui;

import org.apache.commons.io.FilenameUtils;
import org.openmarkov.core.exception.ParserException;
import org.openmarkov.core.exception.UnrecoverableException;
import org.openmarkov.core.io.database.CaseDatabase;
import org.openmarkov.core.io.database.CaseDatabaseWriter;
import org.openmarkov.core.io.database.plugin.CaseDatabaseManager;
import org.openmarkov.core.io.exception.NoReaderForExtension;
import org.openmarkov.core.io.format.annotation.NoReaderForFileException;
import org.openmarkov.core.localize.StringDatabase;
import org.openmarkov.core.model.network.ProbNet;
import org.openmarkov.dbgenerator.DBGenerator;
import org.openmarkov.gui.dialog.io.*;
import org.openmarkov.gui.dialog.io.DBWriterOMFileChooser;
import org.openmarkov.gui.dialog.io.NetworkOMFileChooser;
import org.openmarkov.gui.exception.CorruptNetworkFile;
import org.openmarkov.gui.loader.element.OpenMarkovLogoIcon;
import org.openmarkov.gui.window.MainGUI;
import org.openmarkov.gui.window.MainPanel;
import org.openmarkov.gui.window.edition.NetworkPanel;
import javax.swing.*;
import java.io.File;
import java.io.IOException;
import java.nio.file.FileSystems;

/**
 * GUI to the DBGenerator option
 *
 * @author fjdiez
 * @author ibermejo
 * @version 1.0
 * @since OpenMarkov 1.0
 */
public class DBGeneratorGUI extends javax.swing.JDialog {
    /**
     * Prefixed elements of the combobox.
     */
    private static final String[] CASES_VALUES = { "100", "1000", "5000", "10000", "100000" };
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton cancelButton;
    private static javax.swing.JFileChooser caseDBFileChooser;
    private static javax.swing.JRadioButton fromFileRadioButton;
    private static javax.swing.JRadioButton fromOpenMarkovRadioButton;
    private static javax.swing.JButton generateButton;
    private static javax.swing.JButton loadNetButton;
    private static NetworkOMFileChooser netFileChooser;
    private static javax.swing.JTextPane netFilePathTextPane;
    /**
     * String database
     */
    protected StringDatabase stringDatabase = StringDatabase.getUniqueInstance();
    private ProbNet net;
    private String netFilePath = null;
    private String fileName = null;
    private CaseDatabaseWriter databaseWriter = null;
    /**
     * Messages string resource.
     */
    private JFrame parent;
    private CaseDatabaseManager caseDbManager;
    private javax.swing.JComboBox<String> caseNumber;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.ButtonGroup netButtonGroup;

    /**
     * Constructor for DBGeneratorGUI.
     *
     * @param parent parent
     */
    public DBGeneratorGUI(JFrame parent) {
        super(parent, true);
        this.parent = parent;
        initComponents();
        caseDbManager = new CaseDatabaseManager();
        setIconImage(OpenMarkovLogoIcon.getUniqueInstance().getOpenMarkovLogoIconImage16());
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        setLocationRelativeTo(null);
        netButtonGroup = new ButtonGroup();
        netButtonGroup.add(fromFileRadioButton);
        netButtonGroup.add(fromOpenMarkovRadioButton);
        boolean isOpenNet = MainGUI.INSTANCE.mainPanel.getMainPanelListenerAssistant().getCurrentNetworkPanel() != null;
        if (isOpenNet) {
            net = MainPanel.getCurrentProbNet();
            generateButton.setEnabled(true);
        }
        fromOpenMarkovRadioButton.setEnabled(isOpenNet);
        fromOpenMarkovRadioButton.setSelected(isOpenNet);
        fromFileRadioButton.setSelected(!isOpenNet);
        loadNetButton.setEnabled(!isOpenNet);
        caseNumber.setSelectedIndex(2); // 1000 cases
        caseNumber.setEditable(true);
    }

    // TODO: These FileChoosers can replace those in the initComponents method to
    // improve perfomance,
    // but first, it is needed to study if they won't alter the current behaviour.
    static final DBWriterOMFileChooser COMMON_DB_WRITER_CHOOSER = new DBWriterOMFileChooser(false);
    static final NetworkOMFileChooser COMMON_NETWORK_FILE_CHOOSER = new NetworkOMFileChooser();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        // TODO Performance issue here
        caseDBFileChooser = new DBWriterOMFileChooser(false); // COMMON_DB_WRITER_CHOOSER;
        ((DBWriterOMFileChooser) caseDBFileChooser).setFileFilter("csv");
        // TODO Performance issue here
        netFileChooser = new NetworkOMFileChooser(); // COMMON_NETWORK_FILE_CHOOSER;
        netButtonGroup = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        fromFileRadioButton = new javax.swing.JRadioButton();
        fromOpenMarkovRadioButton = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        netFilePathTextPane = new javax.swing.JTextPane();
        loadNetButton = new javax.swing.JButton();
        generateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        caseNumber = new javax.swing.JComboBox<String>(CASES_VALUES);

        netFileChooser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(stringDatabase.getString("DBGenerator.Title"));
        jPanel8.setBorder(
                javax.swing.BorderFactory.createTitledBorder(stringDatabase.getString("DBGenerator.ChooseNet")));
        fromFileRadioButton.setText(stringDatabase.getString("DBGenerator.LoadNetFromFile"));
        fromFileRadioButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // GEN-FIRST:event_fromFileRadioButton1ActionPerformed
                if (netFilePath == null) {
                    netFilePath = requestNetworkFileToOpen();
                    if (netFilePath != null) {
                        try {
                            net = NetsIO.openNetworkFile(netFilePath).getProbNet();
                        } catch (IOException | ParserException | NoReaderForFileException
                                | CorruptNetworkFile e) {
                            throw new UnrecoverableException(e);
                        }
                    }
                }
                if (netFilePath != null) {
                    loadNetButton.setEnabled(fromFileRadioButton.isSelected());
                    generateButton.setEnabled(net != null);
                }
            }
        });
        fromOpenMarkovRadioButton.setText(stringDatabase.getString("DBGenerator.TakeOpenModelNet"));
        fromOpenMarkovRadioButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromOpenMarkovRadioButtonActionPerformed(evt);
            }
        });
        if (MainGUI.INSTANCE.mainPanel.getMainPanelListenerAssistant().getCurrentNetworkPanel() == null) {
            fromOpenMarkovRadioButton.setEnabled(false);
        }
        netFilePathTextPane.setEditable(false);
        netFilePathTextPane.setEnabled(false);
        jScrollPane5.setViewportView(netFilePathTextPane);
        loadNetButton.setText(stringDatabase.getString("DBGenerator.Open"));
        loadNetButton.setEnabled(false);
        loadNetButton.addActionListener(evt -> {
            // GEN-FIRST:event_loadModelNetButtonActionPerformed
            netFilePath = requestNetworkFileToOpen();
            if (netFilePath == null) {
                return;
            }
            try {
                net = NetsIO.openNetworkFile(netFilePath).getProbNet();
            } catch (NoReaderForFileException | IOException | ParserException | CorruptNetworkFile e) {
                throw new UnrecoverableException(e);
            } finally {
                generateButton.setEnabled(net != null);
            }
        });
        org.jdesktop.layout.GroupLayout jPanel8Layout = new org.jdesktop.layout.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel8Layout.createSequentialGroup().addContainerGap()
                        .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jPanel8Layout.createSequentialGroup()
                                        .add(fromFileRadioButton)
                                        .add(18, 18, 18)
                                        .add(loadNetButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88,
                                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 297,
                                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(fromOpenMarkovRadioButton))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(fromOpenMarkovRadioButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(fromFileRadioButton)
                                        .add(loadNetButton)))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        generateButton.setText(stringDatabase.getString("DBGenerator.Generate"));
        generateButton.setEnabled(false);
        generateButton.addActionListener(evt -> {
            // GEN-FIRST:event_EvaluateButtonActionPerformed
            CaseDatabase database = DBGenerator.generate(net, Integer.parseInt((String) caseNumber.getSelectedItem()));
            String databasePath = null;

            if (caseDBFileChooser.showSaveDialog(DBGeneratorGUI.this) == JFileChooser.APPROVE_OPTION) {
                String filename = caseDBFileChooser.getSelectedFile().getName();
                if (!caseDBFileChooser.getFileFilter().accept(caseDBFileChooser.getSelectedFile())) {
                    if (caseDBFileChooser.getFileFilter() instanceof FileFilterBasic) {
                        filename = caseDBFileChooser.getSelectedFile().getName() + "."
                                + ((FileFilterBasic) caseDBFileChooser.getFileFilter()).getFilterExtension();
                    } else if (!filename.contains(".")) {
                        filename = filename + ".csv";
                    }
                }
                try {
                    databaseWriter = caseDbManager.getWriter(FilenameUtils.getExtension(filename));
                } catch (NoReaderForExtension e) {
                    throw new UnrecoverableException(e);
                }
                generateButton.setEnabled(net != null);
                databasePath = caseDBFileChooser.getSelectedFile().getParent()
                        + FileSystems.getDefault().getSeparator() + filename;
                try {
                    databaseWriter.save(new File(databasePath), database);
                } catch (IOException e) {
                    throw new UnrecoverableException(e);
                }
                JOptionPane.showMessageDialog(null, stringDatabase.getString("DBGenerator.Finished"),
                        stringDatabase.getString("DBGenerator.Title"), JOptionPane.INFORMATION_MESSAGE);
            }
            DBGeneratorGUI.this.setVisible(false);
        });
        cancelButton.setText(stringDatabase.getString("DBGenerator.Cancel"));
        cancelButton.setPreferredSize(new java.awt.Dimension(99, 23));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.setBorder(
                javax.swing.BorderFactory.createTitledBorder(stringDatabase.getString("DBGenerator.NumberOfCases")));
        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel2Layout.createSequentialGroup().add(150, 150, 150)
                        .add(caseNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(caseNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE)));
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup().addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2,
                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel8,
                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                .add(layout.createSequentialGroup()
                        .add(182, 182, 182)
                        .add(generateButton)
                        .add(18, 18, 18)
                        .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE)));
        layout.linkSize(new java.awt.Component[] { cancelButton, generateButton },
                org.jdesktop.layout.GroupLayout.HORIZONTAL);
        layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup().addContainerGap()
                        .add(jPanel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(generateButton)
                                .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel8.getAccessibleContext().setAccessibleName(stringDatabase.getString("DBGenerator.SelectNet"));
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * It asks the user to choose a file by means of a open-file dialog box.
     *
     * @return complete path of the file, or null if the user selects cancel.
     */
    private String requestNetworkFileToOpen() {
        netFileChooser.setDialogTitle(stringDatabase.getString("OpenNetwork.Title"));
        String filePath = null;
        if (netFileChooser.showOpenDialog(this.parent) == JFileChooser.APPROVE_OPTION) {
            filePath = netFileChooser.getSelectedFile().getAbsolutePath();
            fileName = netFileChooser.getSelectedFile().getName();
            netFilePathTextPane.setText(fileName);
        }
        return filePath;
    }

    private void cancelButtonActionPerformed(
            java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }// GEN-LAST:event_cancelButtonActionPerformed

    // GEN-LAST:event_EvaluateButtonActionPerformed

    private void fromOpenMarkovRadioButtonActionPerformed(
            java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fromOpenMarkovRadioButtonActionPerformed
        if (fromOpenMarkovRadioButton.isSelected()) {
            NetworkPanel networkPanel = MainGUI.INSTANCE.mainPanel.getMainPanelListenerAssistant()
                    .getCurrentNetworkPanel();
            net = networkPanel.getProbNet();
            generateButton.setEnabled(net != null);
        }
    }// GEN-LAST:event_fromOpenMarkovRadioButtonActionPerformed

    // GEN-LAST:event_loadModelNetButtonActionPerformed

    // GEN-LAST:event_fromFileRadioButton1ActionPerformed

    // End of variables declaration//GEN-END:variables
}
